### ISSUE TITLE
IIS 7.5 + App_Offline.htm rapid rename - app not always reloading

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#33] opened 2016-10-27 19:00 UTC
_From @andersnm on October 11, 2016 11:1_

I have twice seen our app won't come back properly after quickly moving App_Offline.htm in and out of the app root, f.ex when updating a single dll or aborting a deployment. The workaround is simple, but still an annoyance.

This is an ASP.NET Core 1.0 RTM app targeting net451 hosted on Windows 2008 R2/IIS 7.5/ANCM. ANCM was installed with "DotNetCore.1.0.1-WindowsHosting.exe OPT_INSTALL_REDIST=0". Normally the app serves around a request per second with response times in the range of 10-20 sec, mostly waiting for IO.

Steps to reproduce:
1. Have App_Offline-.htm in the IIS application root (with a dash, ie ignored by ANCM)
2. Rename App_Offline-.htm to App_Offline.htm (remove the dash)
3. Suddenly realize you weren't ready to deploy afterall
4. Rename App_Offline.htm to App_Offline-.htm (put the dash back)

Actual result: Server permanently returns 502 error (the type with red title and border around)

Expected result: App

Workaround: Repeat steps 1-4, ie put App_offline.htm back in and rename again, and it runs fine. 

Speculation: Could there be some kind of race condition unloading/reloading the app if the time spent in step 3 is brief, possibly while there is some load on the app?

Apologies for the lack of the full error message returned by IIS - I had to get the app back online asap and forgot to take note in the heat. The Event Viewer shows a few of these around the time it happened, although they seem to appear always, even when our app reloads successfully:

```
Faulting application name: w3wp.exe, version: 7.5.7601.17514, time stamp: 0x4ce7a5f8
Faulting module name: ntdll.dll, version: 6.1.7601.23392, time stamp: 0x56eb302d
Exception code: 0xc000070a
Fault offset: 0x0009c049
Faulting process id: 0x1224
Faulting application start time: 0x01d217c697dbaa52
Faulting application path: C:\Windows\SysWOW64\inetsrv\w3wp.exe
Faulting module path: C:\Windows\SysWOW64\ntdll.dll
Report Id: c5eb01d8-8f84-11e6-a9a1-0050568563a5
```

I tried but failed to repro the issue in our mostly identical staging environment on Windows2012/IIS 8, although under practically zero load.

_Copied from original issue: aspnet/IISIntegration#281_

**Comment by Tratcher** [comment] 2016-10-27 19:00
@pan-wang this may be related to the issue with loading the config for the wrong site.

**Comment by shirhatti** [comment] 2016-11-17 19:46
@jhkimnew Can you try and repro this?

**Comment by jhkimnew** [comment] 2016-11-18 19:19
One correction. 
The app_offline.htm features works case sensitively. The file name should be app_offline.htm, not App_Offline.htm. 

@Tratcher, I can't reproduce this issue. I'd like to inform that after renaming app_offline.htm or app_offline-.htm, you will need to wait until you get the expected result.  The app_offline.htm feature works based on the file change notification from OS and the change notification can takes longer time, not happening immediately. So, I'd like to suggest you to wait for some time after rename the app_offline.htm file and check if the issue is still reproducible.

**Comment by jhkimnew** [comment] 2017-01-03 23:03
@andersnm, is this issue still reproducible?

**Comment by andersnm** [comment] 2017-01-05 10:27
Yes, this happens consistently on our production IIS7 server.  I am however unable to reproduce on our staging IIS 8 server (although where app is under far less load).

Incidentally we are doing a redeployment of our app today, and just tested to rename App_Offline.htm quickly in and out again: "502 - Web server received an invalid response while acting as a gateway or proxy server."

In fact, the site didn't come back at all, even after multiple renaming attempts - I had to touch web.config for the app load to load again.

I tried with "app_offline.htm" in lowercase but same results.

**Comment by jhkimnew** [comment] 2017-01-05 18:27
@andersnm Would you let me know which version of aspnetcore.dll you are using on the repro machine? The latest version is 7.1.1970.0. If you use quite old build, you would need to upgrade aspnetcore.dll.
The file version can be found from the Detail tab of the properties window of the aspnetcore.dll file with Explorer.  
In the meantime, I will try to reproduce the issue with making some load and update you if I can reproduce with that way.

**Comment by jhkimnew** [comment] 2017-01-05 19:50
@andersnm I can't reproduce the issue. Here is the detail about what I did.

1. On Win8 machine, install the latest ANCM
2. Deploy a simple aspnetcore app on IIS
3. Start stress testing sending lots of requests to the aspnetcore app
4. Create app_offline.htm on the root directory of the aspnetcore app and verify all the request got 502 status code. 
5. Rename app_offline.htm to app_offline-.htm and verify all the request get 200 status code.
6. Rename app_offline-.htm to app_offline.htm and verify all the request get 502 status code.
7. Repeat the step 5 and 6 

Considering this issue is not reproducible, I can't investigate futher. 
Would you try to find a repro step or repro conditions? Is the issue happending with any condition or always?

**Comment by andersnm** [comment] 2017-01-09 10:08
Thanks for looking into @jhkimnew!

The aspnetcore.dll version is 7.1.1967. 

I tested a copy of the app binaries on the same server in a different IIS app/pool, and without load, but still get a permanent 502 after removing app_offline.htm. It appears to happen always.

This is an old server, and has shown erratic behaviour lately so I am wary to request any further upgrades on it. It is more likely we will move our application to a newer server and can hopefully forget about this. 

The only repro condition I can think of is to try with IIS 7.5 instead. Afaik Win8 runs IIS8 where I couldn't repro either, but f.ex Win7 runs IIS7.5. 

I am totally open to this being a server-specific issue (re: erratic behavior), but I don't have access to any additional IIS7.5 machines to test and verify myself. If app_offline.htm works on IIS7.5 for other people I'm fine to close this issue.

**Comment by jhkimnew** [comment] 2017-01-09 20:49
@andersnm 
I'd like to inform that there was some bug fixes/refactoring regarding File change notification on 8/22/2016. 
However, you are using 7.1.1967 which is published on 6/23/2016 and so you are using quite old version now and probably your issue is already fixed with the latest aspnecore.dll. 
So, I think you need to try with the latest Aspnetcore.dll and check if the issue is reproducible or not.  

FYI, 
The latest version aspnetcore.dll is bundled with a package called "Windows Server Hosting". You can find it from https://www.microsoft.com/net/download/core#/runtime page.
Chooe "Runtime" and you will see the link for "Windows Server Hosting (x64/x86).exe".
Installing the package on your machine will upgrade aspnetcore.dll as well.

Thanks,
Jeong Hwan Kim

**Comment by shirhatti** [comment] 2017-04-04 01:43
Closing this issue due to inactivity. Reopen if the issue persists..

**Closed as completed by shirhatti** 2017-04-04 01:43 UTC
