### ISSUE TITLE
Azure Web App: Environment variables provided in the arguments attribute aren't interpreted anymore

### ISSUE THREAD

**Issue by Tratcher** [aspnet/AspNetCoreModule#117] opened 2017-06-28 11:07 UTC
_From @toburger on June 28, 2017 8:22_

I use the following library to host my web application: https://github.com/SuaveIO/Suave.IIS

The hosting port gets provided via:
`arguments="%ASPNETCORE_PORT%"`

Since yesterday everything worked normally. The port was parsed and the app worked flawlessly.
But suddenly I've got the dreaded 502 gateway error.

After some debugging I found the reason of the error:
The environment variable doesn't get interpreted anymore. My program receives the plain "%ASPNETCORE_PORT%" string and not the value of the environment variable.

My workaround is to read the environment variable in the application itselft, but I wonder why the behavior has changed and why this is happening exclusively on Azure. I think the aspNetCore module was updated, but I can't find any information about this breaking change.

_Copied from original issue: aspnet/IISIntegration#389_

**Comment by Tratcher** [comment] 2017-06-28 11:09
A new version of AspNetCoreModule is being deployed to Azure. 

@pan-wang was there a change to environment variable resolution in the arguments?
```
    <aspNetCore
	forwardWindowsAuthToken="true"
        startupTimeLimit="20"
        stdoutLogEnabled="true"
        stdoutLogFile="myiiswebname.log"
	processPath="C:\inetpub\wwwroot\myiiswebname\myiiswebname.exe"
        arguments="%ASPNETCORE_PORT% &quot;myiiswebname&quot;">
	<!-- if running on http://localhost/myiiswebname -->
    </aspNetCore>
```

**Comment by pan-wang** [comment] 2017-06-28 17:08
This is by design. As we discussed, ASPNETCORE_PORT is a reserved environment variable and should only be set by ANCM.

________________________________

**Comment by Tratcher** [comment] 2017-06-28 17:53
Did it previously pick up the value set by ANCM, or only external values?

**Comment by pan-wang** [comment] 2017-06-28 18:34
I looked at code. It is a regression from the code refactoring.

**Comment by pan-wang** [comment] 2017-06-28 20:24
I think the right coding pattern for customer should be reading the environment variables from the application instead of using commandline parameters

**Comment by Tratcher** [comment] 2017-06-28 20:40
@toburger Out of curiosity what were you doing with the ASPNETCORE_PORT value when passed in via command line? When running behind ANCM, IISIntegration reads this value for you and sets up Kestrel.

**Comment by toburger** [comment] 2017-06-29 09:44
I'm not the author of the library but I think the intention was to not rely on some global state which might or might not be set and instead pass the port explicitly to the self hosting program.
This also allows the caller of the program to provide some custom port if needed.

**Comment by Tratcher** [comment] 2017-06-29 14:19
There's no need. We manage that state on behalf of the app via UseIISIntegration. This even overrides settings provided directly to Kestrel, so they're likely doing redundant work.

Taking the port as a command line parameter when running the app elsewhere is fine. I don't think you need to change anything in SuavelO.

**Comment by Tratcher** [comment] 2017-06-29 14:26
Wait, SuaveIO doesn't use any ASP.NET Core packages? It's a completely independent framework running behind AspNetCoreModule?

AspNetCoreModule is not supported as a standalone component, it's part of the ASP.NET Core framework. We often coordinate changes between the various components that may break 3rd parties that get out of sync.

**Comment by davidfowl** [comment] 2017-06-29 14:35
Right, Suave should depend on the http platform handler.

**Comment by Dzoukr** [comment] 2017-07-06 12:29
Thanks @davidfowl, but http platform handler is deprecated, right? I saw this announcement - https://github.com/aspnet/Announcements/issues/164

Or there is plan to have them both side-by-side?

Thanks for any hint.

**Comment by Tratcher** [comment] 2017-07-06 12:43
@Dzoukr ASP.NET Core stopped using it, but other things still do.

**Comment by Dzoukr** [comment] 2017-07-06 20:02
@Tratcher HttpPlatformHandler looks quite "dead" to me. I mean, it works, but some great features like app_offline.htm are not there and that was the reason for me to move to AspNetCoreModule. But now I see that it should not be used as standalone component. So it is strange situation right now. Are there any plans to backport stuff like app_offline.htm to HttpPlatformHandler?

**Comment by Tratcher** [comment] 2017-07-06 22:19
Not that I'm aware of, but that's owned by a different team now so I haven't been tracking it. Ask over here: https://forums.iis.net/1173.aspx

**Comment by shirhatti** [comment] 2018-02-14 08:45
Closing this issue as the discussion seems to have been resolved.

**Closed as completed by shirhatti** 2018-02-14 08:45 UTC
