### ISSUE TITLE
502 when using proxy

### ISSUE THREAD

**Issue by toblea** [aspnet/AspNetCoreModule#79] opened 2017-03-02 09:50 UTC
Our customers started reporting that they were unable to access our website when using a proxy (Client -> Web proxy -> Load Balancer -> WS2k8R2/IIS7.5/ANCM -> Kestrel).
They were all getting:
> 502 - web server received an invalid response while acting as a gateway or proxy server

After _a lot_ of investigations (setting up proxies/new webservers/new load balancers and so on) I finally was able to reproduce and find the problem.

The error occurred when the client was passing two IP addresses in the X-Forwarded-For request header, having a comma separating them:
    `X-Forwarded-For: <Client_IP>, <Proxy_IP>`

It is easy to reproduce the problem by just creating a request and passing to IP's and a comma.
Removing the comma makes it work again.

**Comment by Tratcher** [comment] 2017-03-02 13:42
This message is usually caused by an exception in your application. Turn on logging to find out what happened.

**Comment by toblea** [comment] 2017-03-02 18:42
@Tratcher Yes, I tried that. The request never reaches the web application:

```
Hosting environment: Staging
Content root path: C:\inetpub\wwwroot\nisse
Now listening on: http://localhost:10487
Application started. Press Ctrl+C to shut down.
```

**Comment by toblea** [comment] 2017-03-10 13:52
@Tratcher Using the _IIS Advanced Logging Module_ I got the following info by using Postman to create GET requests with X-Forwarded-For headers (random IP's: `"127.0.0.1, 10.0.1.1"`):

```
#Software: IIS Advanced Logging Module
#Version: 1.0
#Start-Date: 2017-03-10 13:37:37.442
#Fields:  X-Forwarded-For
"127.0.0.1                         "
"127.0.0.1 0 2 . h t m   0ž/    H›"
"127.0.0.1 0 2 . h t m   0ž/    H›"
"127.0.0.1 0 2 . h t m   0ž/    H›"
"127.0.0.1 0 2 . h t m   0ž/    H›"
"127.0.0.1 0 2 . h t m   0ž/    H›"
"127.0.0.1 0 2 . h t m   0ž/   "
"127.0.0.1 0 2 . h t m   0ž/   "
"127.0.0.1 0 2 . h t m   0ž/   "
"127.0.0.1 0 2 . h t m   0ž/   "
"127.0.0.1 0 2 . h t m   0ž/   "
"127.0.0.1 0 2 . h t m   0ž/   "
```

**Comment by shirhatti** [comment] 2017-04-03 18:39
> It is easy to reproduce the problem by just creating a request and passing to IP's and a comma.

Did you repro against Kestrel directly or against IIS/ANCM+Kestrel?

Also, can you share the raw request you used?

**Comment by toblea** [comment] 2017-04-03 20:46
@shirhatti It works fine directly against Kestrel, but not against IIS/ANCM+Kestrel.

```
GET http://[IP_NUMBER]/ HTTP/1.1
X-Forwarded-For: 127.0.0.1, 127.0.0.1
Host: [IP_NUMBER]
```

**Comment by muratg** [comment] 2017-12-20 22:56
@toblea Looks like there wasn't much traction on this bug. I'll close this, but if you still have issues, please let us know and we'll reactivate. Or better yet, file another one with your current details. Thanks.

**Comment by muratg** [comment] 2017-12-20 22:56
@toblea Looks like there wasn't much traction on this bug. I'll close this, but if you still have issues, please let us know and we'll reactivate. Or better yet, file another one with your current details. Thanks.

**Comment by toblea** [comment] 2017-12-21 07:37
😢

**Comment by muratg** [comment] 2017-12-21 18:47
@toblea You're still having issues on this I assume. :bug: 

Any more investigations and/or findings on your side?

**Comment by toblea** [comment] 2017-12-21 21:02
No, let's close it. Since no one else experience the same, I will go for the hack and stop using the IIS integration when possible.

**Closed as completed** 2017-12-21 21:14 UTC
