### ISSUE TITLE
Intermittent 502.3 (Error code 2147954402) error

### ISSUE THREAD

**Issue by joshmouch** [aspnet/AspNetCoreModule#287] opened 2018-02-06 16:47 UTC
I am occasionally seeing a 502.3 error in our logs with the error code 2147954402.  I've pasted part of the FREB log.  I've enabled the stdout, and there are no errors outputed there.  There's exactly two minutes between last FREB entry before AspNetCoreModule, and the AspNetCoreModule entry.

```

88. | GENERAL_SET_REQUEST_HEADER | HeaderName="MS-ASPNETCORE-TOKEN", HeaderValue="7b115656-1a35-407f-9db2-7e0e4d32c068", Replace="true" | 21:06:53.057
-- | -- | -- | --
89. | GENERAL_SET_REQUEST_HEADER | HeaderName="X-Forwarded-For", HeaderValue="168.62.238.134:5017, 168.62.238.134:5017", Replace="true" | 21:06:53.057
90. | GENERAL_SET_REQUEST_HEADER | HeaderName="X-Forwarded-Proto", HeaderValue="https, https", Replace="true" | 21:06:53.057
91. | GENERAL_SET_REQUEST_HEADER | HeaderName="MS-ASPNETCORE-CLIENTCERT", HeaderValue="", Replace="true" | 21:06:53.057
92. | GENERAL_SET_REQUEST_HEADER | HeaderName="Connection", HeaderValue="", Replace="true" | 21:06:53.057
93. | MODULE_SET_RESPONSE_ERROR_STATUSWarning | ModuleName="AspNetCoreModule", Notification="EXECUTE_REQUEST_HANDLER", HttpStatus="502", HttpReason="Bad Gateway", HttpSubStatus="3", ErrorCode="2147954402", ConfigExceptionInfo="" | 21:08:55.104
94. | NOTIFY_MODULE_COMPLETION | ModuleName="AspNetCoreModule", Notification="EXECUTE_REQUEST_HANDLER", fIsPostNotificationEvent="false", CompletionBytes="0", ErrorCode="The operation completed successfully.  (0x0)" | 21:08:55.104
95. | NOTIFY_MODULE_END | ModuleName="AspNetCoreModule", Notification="EXECUTE_REQUEST_HANDLER", fIsPostNotificationEvent="false", NotificationStatus="NOTIFICATION_CONTINUE" | 21:08:55.104
96. | NOTIFY_MODULE_START | ModuleName="DynamicCompressionModule", Notification="RELEASE_REQUEST_STATE", fIsPostNotification="true" | 21:08:55.104
97. | NOTIFY_MODULE_END | ModuleName="DynamicCompressionModule", Notification="RELEASE_REQUEST_STATE", fIsPostNotificationEvent="true", NotificationStatus="NOTIFICATION_CONTINUE" | 21:08:55.104
98. | NOTIFY_MODULE_START | ModuleName="RewriteModule", Notification="RELEASE_REQUEST_STATE", fIsPostNotification="true" | 21:08:55.104
99. | NOTIFY_MODULE_END | ModuleName="RewriteModule", Notification="RELEASE_REQUEST_STATE", fIsPostNotificationEvent="true", NotificationStatus="NOTIFICATION_CONTINUE" | 21:08:55.104
100. | NOTIFY_MODULE_START | ModuleName="HttpCacheModule", Notification="UPDATE_REQUEST_CACHE", fIsPostNotification="false" | 21:08:55.104
 


```

**Comment by joshmouch** [comment] 2018-02-09 16:52
I got a few more of these today.  Is there any other information I can provide to diagnose this?

**Comment by jkotalik** [comment] 2018-02-09 19:23
Seems that ANCM is timing out when trying to start kestrel. The startup timeout is 2 minutes, so ANCM thinks that Kestrel and you application has not started. If you can provide any windows event logs and your web.config file, that would help diagnose this.

**Comment by juggleking** [comment] 2018-02-12 12:27
I have the same issue. For the first user , that logs into our application , it works , when logging out , and logging backagain with the same user ( or another ) , the first page hangs for 2 minutes and gets through , or shows the  502.3 error in our logs with the error code 2147954402. I don't know what the issue is. 

I am using IIS + asp core 1.1 on a windows 20012 r2

[FailedRequest.zip](https://github.com/aspnet/AspNetCoreModule/files/1716235/FailedRequest.zip).

I have 3 versions of the asp core installed 1.0.5.4881 / 1.1.30503.82 / 1.1.2.1514.
Also on another server with with other versions installed I have same issue.

Strange thing is , when I the 'disable cache' in chrome everything works fine. 

Does anybody have a clue ?

**Comment by jkotalik** [comment] 2018-02-12 21:46
cc/ @pan-wang, I'll do a bit of investigation here, but you probably have a better idea of what is going on. Could be an issue with caching.

**Comment by shirhatti** [comment] 2018-02-13 01:50
> Seems that ANCM is timing out when trying to start kestrel. The startup timeout is 2 minutes, so ANCM thinks that Kestrel and you application has not started

@jkotalik The process started successfully. Looks like @joshmouch is hitting the request timeout.

@joshmouch I looked at your FREB logs, and there's nothing here to indicate what's going on besides your backend timing out.

If you believe some requests legitimately are expected to take more than two minutes, your quick fix is to increase your requestTimeout in your web.config
If not, the problem lies outside of ANCM, but in your application. Your best bet here is to add logging to your backend application to see why your requests are taking longer than two minutes.
The 2147954402 error you're seeing is just WinInet timing out.

As for disabling caching, I'm going to wager a guess that's an artifact of your application. I'm very curious as to why your seeing that behavior

I'm closing this issue as it's not actionable by us in any which way. Feel free to re-open the issue if you have more information

**Closed as completed by shirhatti** 2018-02-13 01:50 UTC

**Comment by dombarnes** [comment] 2018-05-15 16:29
How many instances do you have running and do you have ARR Affinity turned on? If its off and you have multiple instances, one could just be failing to start. Thats what we had an issue with.
If you have ARR turned on a cookie is set that sends you to the same instance every time so if you had initially hit a down instance, you'd keep hitting that one. 
Inside the Diagnose Problems blade in the App Service there is a sidebar option to restart the whole w3wp worker instance(s) that may help.
Not sure if that helps in any way.

**Comment by joshmouch** [comment] 2018-05-15 17:57
@dombarnes In my case, ARR Affinity is turned off.
