### ISSUE TITLE
Inprocess: AV when recycling worker process

### ISSUE THREAD

**Issue by jhkimnew** [aspnet/AspNetCoreModule#192] opened 2017-10-18 00:14 UTC
STEPS TO REPRO:

1. Deploy the Inprocess AspnetCore web application of "NativeIISSample" which is available in IISIntegration repo to full IIS server.
2. Send a request to the web application
3. Open Inetmgr.exe and recycle the DefaultAppPool

EXPECTED:

No AV

ACTUAL:

Below AV happens because iiscore!W3_SERVER::RecycleProcess is called after the object is already gone. 

<><><>
(4828.35c8): Access violation - code c0000005 (first chance)
First chance exceptions are reported before any exception handling.
This exception may be expected and handled.
*** WARNING: Unable to verify checksum for C:\WINDOWS\system32\inetsrv\aspnetcore.dll
iiscore!W3_SERVER::RecycleProcess+0x7:
00007ffa`eb1f5767 488b01          mov     rax,qword ptr [rcx] ds:00000000`00000000=????????????????

0:007> dv
           **this = <value unavailable>**
      pszReason = 0x00007ffa`e8e2ddf0 "AspNetCore Recycle Process on Configuration Change"

0:007> kn
 # Child-SP          RetAddr           Call Site
00 0000008a`51aff618 00007ffa`e8df8e1c iiscore!W3_SERVER::RecycleProcess+0x7 [inetsrv\iis\iisrearc\iis70\core\w3server.h @ 315] 
01 0000008a`51aff620 00007ffa`e8dfa5ec aspnetcore!ASPNETCORE_CONFIG::~ASPNETCORE_CONFIG+0x8c [c:\gitroot\aspnetcoremodule\src\aspnetcore\src\aspnetcoreconfig.cxx @ 16] 
02 0000008a`51aff680 00007ffa`e8dfa76f aspnetcore!ASPNETCORE_CONFIG::`scalar deleting destructor'+0x2c
03 0000008a`51aff6b0 00007ffa`eb1d4404 aspnetcore!ASPNETCORE_CONFIG::CleanupStoredContext+0x4f [c:\gitroot\aspnetcoremodule\src\aspnetcore\inc\aspnetcoreconfig.h @ 60] 
04 0000008a`51aff700 00007ffa`eb1d434e iiscore!CONTEXT_CONTAINER::Cleanup+0xa4 [inetsrv\iis\iisrearc\iis70\core\contextcontainer.cxx @ 50] 
05 0000008a`51aff730 00007ffa`eb1d29b2 iiscore!CONTEXT_CONTAINER::~CONTEXT_CONTAINER+0x2e [inetsrv\iis\iisrearc\iis70\core\contextcontainer.h @ 46] 
06 0000008a`51aff760 00007ffa`eb1d2a14 iiscore!W3_APPLICATION::~W3_APPLICATION+0xca [inetsrv\iis\iisrearc\iis70\core\w3application.h @ 58] 
07 0000008a`51aff790 00007ffa`eb1d3b31 iiscore!W3_APPLICATION::`scalar deleting destructor'+0x14
08 0000008a`51aff7c0 00007ffa`eb1d3af4 iiscore!W3_METADATA::~W3_METADATA+0x21 [inetsrv\iis\iisrearc\iis70\core\w3metadata.h @ 229] 
09 0000008a`51aff7f0 00007ffa`fc4f668f iiscore!W3_METADATA::`scalar deleting destructor'+0x14
0a 0000008a`51aff820 00007ffa`fc516c74 iisutil!TREE_HASH_TABLE::DeleteNode+0x1f [inetsrv\iis\iisrearc\core\common\util\treehash.cxx @ 84] 
0b 0000008a`51aff850 00007ffa`eb1f5eac iisutil!TREE_HASH_TABLE::Clear+0x44 [inetsrv\iis\iisrearc\core\common\util\treehash.cxx @ 144] 
0c 0000008a`51aff880 00007ffa`eb1f5d0b iiscore!W3_SERVER::TerminateGlobalModules+0x40 [inetsrv\iis\iisrearc\iis70\core\w3server.cxx @ 1466] 
0d 0000008a`51aff8b0 00007ffa`eb2032cd iiscore!W3_SERVER::Terminate+0x2ab [inetsrv\iis\iisrearc\iis70\core\w3server.cxx @ 1040] 
0e 0000008a`51aff8f0 00007ffa`f36bb8ec iiscore!IISCORE_PROTOCOL_MANAGER::StopListenerChannel+0x6d [inetsrv\iis\iisrearc\iis70\core\iiscore_protocol_manager.cxx @ 793] 
0f 0000008a`51aff920 00007ffa`f36bbdd5 w3wphost!LISTENER_CHANNEL::HandleStopListenerChannel+0x98 [inetsrv\iis\iisrearc\iisplus\w3wphost\listener_channel.cxx @ 966] 
10 0000008a`51aff970 00007ffa`f36b1106 w3wphost!LISTENER_CHANNEL_STOP_WORKITEM::ExecuteWorkItem+0x15 [inetsrv\iis\iisrearc\iisplus\w3wphost\listener_channel_workitem.cxx @ 60] 
11 0000008a`51aff9a0 00007ffa`eb07ce6c w3wphost!W3WP_HOST::ExecuteWorkItem+0x16 [inetsrv\iis\iisrearc\iisplus\w3wphost\w3wphost.cxx @ 4966] 
12 0000008a`51aff9d0 00007ffb`0884f689 vfbasics!AVrfpRtlWorkerCallback+0x3c [onecore\base\avrf\vrfcommon\threadpool.c @ 2197] 
13 0000008a`51affa50 00007ffb`088519ac ntdll!RtlpTpWorkCallback+0x169 [minkernel\threadpool\compat\worker.c @ 279] 
14 0000008a`51affb30 00007ffb`069d2774 ntdll!TppWorkerThread+0x6ec [minkernel\threadpool\ntdll\worker.c @ 1109] 
15 0000008a`51affe40 00007ffb`08880d51 KERNEL32!BaseThreadInitThunk+0x14 [base\win32\client\thread.c @ 64] 
16 0000008a`51affe70 00000000`00000000 ntdll!RtlUserThreadStart+0x21 [minkernel\ntdll\rtlstrt.c @ 997]

**Comment by shirhatti** [comment] 2017-10-19 00:03
Dupe of #194

**Closed as completed by shirhatti** 2017-10-19 00:03 UTC
