### ISSUE TITLE
ANCM/IIS ServerSentEvents won't work correctly (due to caching?) 

### ISSUE THREAD

**Issue by moozzyk** [aspnet/AspNetCoreModule#16] opened 2016-10-03 17:48 UTC
When using ServerSentEvents the messages pushed to the client are not delivered immediately. Rather they are cached somewhere and are delivered when subsequent messages are being sent. 
When I tried this my client (JavaScript) was always one message behind - i.e. when I pushed a message from the server the client would receive not the message I pushed but the previous one. This does not happen when using Kestrel directly. 
Also we hit this when using SignalR JS Client (https://github.com/aspnet/SignalR-Server/issues/221) and also in a completely different environment when prototyping for new SiganlR.

**Comment by muratg** [comment] 2017-02-03 22:59
@shirhatti @pan-wang could you guys take a look?  This is possibly blocking Event source and SSE transport in SignalR.

**Comment by pan-wang** [comment] 2017-02-08 18:54
ANCM did pass the full response to IIS main pipeline. However, it seems only partial response was flushed to the wire after dynamic compression. Looking at the root cause and see how we can improve it at IIS dynamic compression module.

**Comment by muratg** [comment] 2017-03-31 21:45
**ping** @shirhatti @pan-wang

**Comment by muratg** [comment] 2017-12-20 22:20
@bangbingsyb Does the new IIS compression module solve this issue?

**Comment by bangbingsyb** [comment] 2017-12-21 00:12
@anurse I will test this with the new compression scheme.

**Comment by yasmoradi** [comment] 2018-04-25 08:16
If you use ASP.NET Core's ResponseCompression middleware instead of relying on IIS for this, you won't face such a ridicules problem! (-:

**Comment by bangbingsyb** [comment] 2018-04-25 18:38
@muratg @Tratcher @ysmoradi We've extensively tested the new IIS Compression extension that will be released within two weeks. I believe it will definitely solve this problem. 

@jhkimnew  has tested it by using an app that will flush 1 char by 1 char, and sleep several seconds between adjacent flushes. This is an artificial scenario where the compression doesn't bring any benefit. But it is a good scenario to make sure the new compression extension doesn't buffer data across flushes. We indeed see the client gets 1 char by 1 char timely, while we see the client gets all 10-20 chars altogether after the last flush with the old gzip.dll.

**Comment by bangbingsyb** [comment] 2018-04-26 17:37
@muratg @Tratcher @ysmoradi : BTW, is it possible you guys provide us a sample app that uses ServerSentEvents? Although in theory, from IIS perspective, it should have no difference from @jhkimnew 's test, but it would always be beneficial to validate the exact scenario.

**Comment by Tratcher** [comment] 2018-04-26 17:48
@BrennanConroy @anurse for a sample.

**Comment by analogrelay** [comment] 2018-04-26 18:46
The easiest sample would be to take something like the SignalR Samples (https://github.com/aspnet/SignalR/tree/dev/samples/SignalRSamples) and run it behind IIS, specifying Server-Sent Events as the transport.

We have no readily available stand-alone Server-Sent Events sample, but it's relatively straightforward to write from [the spec](https://www.w3.org/TR/2009/WD-eventsource-20090421/)

**Comment by bariscaglar** [comment] 2018-05-08 17:42
@bangbingsyb, @jhkimnew have we tried this?

**Comment by bangbingsyb** [comment] 2018-05-09 00:55
@bariscaglar No, we haven't tried yet.
@jhkimnew Could you help test non-delay mode dynamic compression using that sample app? Thanks.

**Comment by shirhatti** [comment] 2018-06-28 18:00
I'm closing this issue since the consensus we reached was to disable compression for the text/event-stream MIME type as part of the ANCM installer. This was resolved by PR 123339 in VSTS

**Closed by shirhatti** 2018-06-28 18:00 UTC
